language: php
php:
  - 7.4
 
before_script: 
  - composer install

script: 
  - ./vendor/bin/phpcs --standard=test/phpcs.xml test/file.php | grep -q "FOUND 3 ERRORS AFFECTING 3 LINES"
  - ./vendor/bin/phpcbf --standard=test/phpcs.xml test/file.php | grep -q "A TOTAL OF 3 ERRORS WERE FIXED IN 10 FILE"
