language: php
php:
  - 7.4
 
before_script: 
  - composer install

script:
  - ./vendor/bin/phpcs --standard=test/phpcs.xml test/file.php | grep -q "FOUND 7 ERRORS AFFECTING 6 LINES"
  - ./vendor/bin/phpcbf --standard=test/phpcs.xml test/file.php | grep -q "A TOTAL OF 7 ERRORS WERE FIXED IN 1 FILE"
